"""`mf docs render [--check]` — generate the docs that mirror the code (M11, ТЗ §2.3, §8.2).

Phases, modes, events and the degradation table are defined once, in Python (M11); the markdown
views under `docs/` are generated from those modules and `--check` fails when a file on disk has
drifted from its source of truth. `docs/permissions.md` is the README block of §8.2 and is built from
`hooks/allowlist.txt` — that file arrives with wave W2, so until then the target is skipped with a
note instead of inventing hosts.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from . import events, fallbacks, limits, modes, phases, pylauncher, state_io

DOCS_DIRNAME = "docs"
ALLOWLIST_RELATIVE = "hooks/allowlist.txt"

GENERATED_HEADER = "<!-- generated by `mf docs render` — do not edit by hand (M11) -->"

MCP_NAMESPACES: tuple[str, ...] = (
    "mcp__plugin_memoforge_legal-data-hunter__*",
    "mcp__plugin_memoforge_courtlistener__*",
    "mcp__plugin_memoforge_legalviz__*",
    "mcp__plugin_memoforge_uk-legal__*",
    "mcp__plugin_memoforge_justicelibre__*",
    "mcp__plugin_memoforge_opencaselaw__*",
    "mcp__plugin_memoforge_federal-regulations__*",
    "mcp__plugin_memoforge_lex__*",
    "mcp__plugin_memoforge_casus__*",
    "mcp__plugin_memoforge_fas-search__*",
)
"""§8.2: the MCP namespaces of the bundled servers the README block allows (D-105 and D-148 add
two each; D-160 adds the US regulations server; D-161 the UK Lex server; D-184 the RU servers)."""

BASH_RULE_PLUGIN_ROOT = "${CLAUDE_PLUGIN_ROOT}"
"""D-26: the `Bash(...)` rule keeps the placeholder, so `docs/permissions.md` is machine-independent."""


def docs_dir(root: Path | None = None) -> Path:
    """`<plugin_root>/docs`."""
    return (root or pylauncher.plugin_root()) / DOCS_DIRNAME


# --- generators -----------------------------------------------------------


def render_phases() -> str:
    """`docs/phases.md` from `phases.py`."""
    lines = [
        "# Phases (v2)",
        "",
        GENERATED_HEADER,
        "",
        "Source of truth: `scripts/memoforge/phases.py` (ТЗ §2.1). A terminal phase is written only",
        "after `mf finalize` produced `deliverable.{docx|md}` and `summary.md` (M9).",
        "",
        "| # | phase | kind | label (D-95) |",
        "|---|---|---|---|",
    ]
    for index, phase in enumerate(phases.PHASES, start=1):
        if phases.is_terminal(phase):
            kind = "terminal"
        elif phases.is_gate(phase):
            kind = "gate"
        else:
            kind = "work"
        lines.append(f"| {index} | `{phase}` | {kind} | {phases.label(phase)} |")
    lines.extend(
        [
            "",
            f"Initial phase: `{phases.INITIAL_PHASE}`.",
            "",
            "Gates (segment boundaries, M8): " + ", ".join(f"`{name}`" for name in phases.GATES) + ".",
            "",
            "Terminal phases: " + ", ".join(f"`{name}`" for name in phases.TERMINAL) + ".",
            "",
        ]
    )
    return "\n".join(lines)


def render_modes() -> str:
    """`docs/modes.md` from `modes.py` (§2.3)."""
    keys = [
        "researcher_layers",
        "reviewer_list",
        "max_iterations",
        "client_polish_enabled",
        "max_client_polish",
        "template_id",
        "source_review_gate",
        "lint_fix_rounds",
        "intake_max_questions",
        "mcp_budget",
    ]
    names = sorted(modes.MODES)
    lines = [
        "# Modes (v2)",
        "",
        GENERATED_HEADER,
        "",
        "Source of truth: `scripts/memoforge/modes.py` (ТЗ §2.3). The `source_review_gate` priority",
        "chain is `userConfig on|off` > mode > `auto`.",
        "",
        "| field | " + " | ".join(names) + " |",
        "|---|" + "---|" * len(names),
    ]
    for key in keys:
        cells = [_cell(modes.MODES[name].get(key)) for name in names]
        lines.append(f"| `{key}` | " + " | ".join(cells) + " |")
    lines.extend(
        [
            "",
            f"Default writer model: `{modes.DEFAULT_WRITER_MODEL}`; allowed: "
            + ", ".join(f"`{name}`" for name in limits.ALLOWED_WRITER_MODELS)
            + " (§4.1).",
            "",
            f"Default citation style: `{modes.DEFAULT_CITATION_STYLE}`; allowed: "
            + ", ".join(f"`{name}`" for name in modes.CITATION_STYLES)
            + " (§5.5, D-150/D-152). `inline` links a short parenthetical citation to the source and"
            " keeps the full record in the Sources annex; `footnotes` writes a Word footnote per"
            " citation. Set it per run with"
            " `mf task new --option citation_style=footnotes`, or per template in the template's"
            " own front matter.",
            "",
        ]
    )
    return "\n".join(lines)


def _cell(value: object) -> str:
    if isinstance(value, list):
        return ", ".join(f"`{item}`" for item in value) or "—"
    if isinstance(value, dict):
        return ", ".join(f"{key}: {item}" for key, item in sorted(value.items())) or "—"
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "—"
    return f"`{value}`"


def render_events() -> str:
    """`docs/events.md` from `events.py` (§7.2)."""
    lines = [
        "# Journal events (v2)",
        "",
        GENERATED_HEADER,
        "",
        "Source of truth: `scripts/memoforge/events.py` (ТЗ §7.2 C/C′). The journal is always",
        f"`<work_dir>/{events.EVENTS_FILENAME}`; one line per event, at most",
        f"{limits.EVENT_LINE_MAX_BYTES} bytes, appended under `{events.EVENTS_LOCK_FILENAME}`.",
        "Hook events are at-least-once and deduplicated on read by `event_key`.",
        "",
        "| event |",
        "|---|",
    ]
    for name in sorted(events.EVENT_TYPES):
        lines.append(f"| `{name}` |")
    lines.extend(
        [
            "",
            "Severities: " + ", ".join(f"`{name}`" for name in events.SEVERITIES) + ".",
            "",
            "Record shape: `{ts, event, actor, severity, phase, step_id, event_key, data}`.",
            "",
        ]
    )
    return "\n".join(lines)


def render_always_deliver() -> str:
    """`docs/always-deliver.md` from `fallbacks.py` (§0.4: the v1 reference becomes generated)."""
    lines = [
        "# Always-deliver: the degradation table",
        "",
        GENERATED_HEADER,
        "",
        "Source of truth: `scripts/memoforge/fallbacks.py` (M9, ТЗ §2.1, §5.5). Every row leaves a",
        "deliverable: `mf finalize` writes `deliverable.{docx|md}` and `summary.md` before any",
        "terminal phase is recorded, and `mf finalize --salvage` does so without `jsonschema` and on",
        "a corrupt `state.json`.",
        "",
        "| condition | phase | action | banner |",
        "|---|---|---|---|",
    ]
    for row in fallbacks.FALLBACKS:
        banner = f"`{row['banner_id']}`" if row["banner_id"] else "—"
        phase = f"`{row['phase']}`" if row["phase"] else "any"
        lines.append(f"| `{row['condition_key']}` | {phase} | {row['action']} | {banner} |")
    lines.extend(["", "## Banner texts", ""])
    for row in fallbacks.FALLBACKS:
        if not row["banner_id"]:
            continue
        lines.append(f"- **`{row['banner_id']}`** — {row['banner_text']}")
    lines.append("")
    return "\n".join(lines)


def read_allowlist(root: Path | None = None) -> list[str] | None:
    """Hosts of `hooks/allowlist.txt`, or None when the file does not exist yet (wave W2)."""
    path = (root or pylauncher.plugin_root()) / ALLOWLIST_RELATIVE
    try:
        raw = path.read_text(encoding="utf-8-sig")
    except OSError:
        return None
    hosts = []
    for line in raw.split("\n"):
        line = line.split("#", 1)[0].strip()
        if line and line not in hosts:
            hosts.append(line)
    return hosts


def render_permissions(root: Path | None = None) -> str | None:
    """`docs/permissions.md` — the README block of §8.2; None when there is no allowlist yet."""
    hosts = read_allowlist(root)
    if hosts is None:
        return None
    rules = []
    for host in hosts:
        rules.append(f'"WebFetch(domain:{host})"')
        rules.append(f'"WebFetch(domain:*.{host})"')
    for namespace in MCP_NAMESPACES:
        rules.append(f'"{namespace}"')
    rules.append(f'"Bash({BASH_RULE_PLUGIN_ROOT}/scripts/mf *)"')

    lines = [
        "# Permissions",
        "",
        GENERATED_HEADER,
        "",
        "A plugin cannot ship permission rules, so paste this block into `~/.claude/settings.json`",
        "(ТЗ §8.2). `Agent(memoforge:*)` is deliberately absent: globs for `Agent` are not confirmed.",
        "",
        "```json",
        '{"permissions": {"allow": [',
        ",\n".join(f"  {rule}" for rule in rules),
        "]}}",
        "```",
        "",
        f"В правиле `Bash(...)` замените `{BASH_RULE_PLUGIN_ROOT}` на путь установки плагина.",
        "",
        "**In Cowork these rules do not apply.** There Bash and WebFetch arrive as",
        "`mcp__workspace__*`, which the allow list above does not cover; the only protection is the",
        "`permission_gate` hook of §8.1.",
        "",
    ]
    return "\n".join(lines)


def targets(root: Path | None = None) -> dict:
    """`{filename: content|None}` for every generated document; None means «skip with a note»."""
    return {
        "phases.md": render_phases(),
        "modes.md": render_modes(),
        "events.md": render_events(),
        "always-deliver.md": render_always_deliver(),
        "permissions.md": render_permissions(root),
    }


# --- command --------------------------------------------------------------


def run_render(args: argparse.Namespace) -> dict:
    """`mf docs render [target] [--check]` — write or verify the generated documents."""
    root = Path(args.root) if args.root else pylauncher.plugin_root()
    directory = docs_dir(root)
    generated = targets(root)

    wanted = args.target
    if wanted and wanted != "all":
        name = wanted if wanted.endswith(".md") else f"{wanted}.md"
        if name not in generated:
            return {"errors": [f"unknown_docs_target: {wanted}"], "known": sorted(generated)}
        generated = {name: generated[name]}

    written: list[str] = []
    unchanged: list[str] = []
    skipped: list[dict] = []
    mismatched: list[dict] = []

    for name, content in generated.items():
        path = directory / name
        if content is None:
            skipped.append(
                {
                    "file": name,
                    "reason": f"{ALLOWLIST_RELATIVE} does not exist yet (wave W2); nothing to generate",
                }
            )
            continue
        current = _read(path)
        if current == content:
            unchanged.append(name)
            continue
        if args.check:
            mismatched.append({"file": name, "exists": current is not None})
            continue
        state_io.write_bytes_atomic(path, content.encode("utf-8"))
        written.append(name)

    result = {
        "docs_dir": str(directory),
        "check": bool(args.check),
        "written": written,
        "unchanged": unchanged,
        "skipped": skipped,
        "mismatched": mismatched,
    }
    if args.check and mismatched:
        result["errors"] = [
            "docs_out_of_date: " + ", ".join(row["file"] for row in mismatched),
        ]
    return result


def _read(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8-sig")
    except OSError:
        return None


def register(subparsers) -> None:
    """Register `mf docs render`."""
    from . import cli

    group = cli.group_subparsers(subparsers, "docs", "generated documentation (M11)")
    parser = group.add_parser("render", help="generate docs/*.md from the code")
    parser.add_argument(
        "target",
        nargs="?",
        default="all",
        help="all | phases | modes | events | always-deliver | permissions",
    )
    parser.add_argument("--check", action="store_true", help="compare only; exit 1 on a mismatch")
    parser.add_argument("--root", default=None, help="plugin root (default: discovery)")
    parser.set_defaults(func=run_render)
