#!/usr/bin/env python
"""Generator of `hooks/hooks.json` from the table of ТЗ §8.1 — run it, never hand-edit the JSON.

Every command hook is emitted in three exec-form variants — `python`, `python3` and `py -3` — so the
row survives whichever interpreter the host actually has on PATH (S-01: on Windows `python3` is the
Store stub). All three fire when all three resolve; that is by design: `permission_gate` is
deterministic, and `progress_logger` deduplicates through the `events/.seen/<event_key>` marker of
§7.2 C. Exec form (`{"command": "python", "args": [...]}`) is what makes `${CLAUDE_PLUGIN_ROOT}`
substitution reliable — no shell, no quoting (`analysis/03-scripts-audit.md` §6).

Two generated fallbacks stay out of the file until asked for:

    --inline-fallback   a `python -c` one-liner of the fetch gate, built from `hooks/allowlist.txt`,
                        for the case where probe P2 shows exec form does not run at all
    --agent-fallback    `^memoforge:(<agent>|…)$` instead of the `^memoforge:` prefix matcher,
                        built from `lib/models.md`, for the case where probe P9 shows that a bare
                        prefix does not match plugin agents

Usage: `python hooks/build_hooks.py` (write) or `python hooks/build_hooks.py --check` (CI).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parents[1]

HOOKS_FILENAME = "hooks.json"
ALLOWLIST_FILENAME = "allowlist.txt"
MODELS_RELATIVE = "lib/models.md"

PLUGIN_ROOT_PLACEHOLDER = "${CLAUDE_PLUGIN_ROOT}"

INTERPRETERS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("python", ()),
    ("python3", ()),
    ("py", ("-3",)),
)
"""§8.1: the three exec-form variants of every command hook, in discovery order (§5.6)."""

FETCH_MATCHER = "^WebFetch$|^mcp__.*fetch$"
AGENT_PREFIX_MATCHER = "^memoforge:"

MCP_MATCHER = "^mcp__"
"""Every MCP tool of the session reaches the accounting hook; `progress_logger` keeps the four
bundled legal servers and drops the rest. A matcher tied to `mcp__plugin_memoforge_` saw nothing at
all on a host that mounts the same servers under its own namespace (`mcp__Legal_Data_Hunter__…`)."""

EVENT_ORDER: tuple[str, ...] = (
    "PreToolUse",
    "PostToolUse",
    "SubagentStart",
    "SubagentStop",
    "Stop",
    "SessionStart",
    "PreCompact",
)

ROWS: tuple[dict, ...] = (
    {
        "event": "PreToolUse",
        "matcher": FETCH_MATCHER,
        "script": "permission_gate.py",
        "args": ("--mode", "fetch"),
    },
    {
        "event": "PreToolUse",
        "matcher": "^WebSearch$",
        "script": "permission_gate.py",
        "args": ("--mode", "websearch"),
    },
    {
        "event": "PreToolUse",
        "matcher": "^Bash$|^mcp__workspace__bash$",
        "script": "permission_gate.py",
        "args": ("--mode", "bash"),
    },
    {
        "event": "PostToolUse",
        "matcher": MCP_MATCHER,
        "script": "progress_logger.py",
        "args": ("--mcp",),
        "async": True,
    },
    {
        "event": "PreToolUse",
        "matcher": "^(Agent|Task)$",
        "script": "progress_logger.py",
        "args": ("--pre",),
        "async": True,
    },
    {
        "event": "SubagentStart",
        "matcher": AGENT_PREFIX_MATCHER,
        "script": "progress_logger.py",
        "args": (),
        "async": True,
        "agent_matcher": True,
    },
    {
        "event": "SubagentStop",
        "matcher": AGENT_PREFIX_MATCHER,
        "script": "progress_logger.py",
        "args": (),
        "async": True,
        "agent_matcher": True,
    },
    {
        "event": "Stop",
        "matcher": None,
        "script": "stop_guard.py",
        "args": (),
    },
    {
        "event": "SessionStart",
        "matcher": "startup|resume",
        "script": "ensure_deps.py",
        "args": (),
        "async": True,
    },
    {
        "event": "PreCompact",
        "matcher": None,
        "script": "progress_logger.py",
        "args": ("--compact",),
    },
)
"""One entry per row of the §8.1 table, in table order."""

FILE_COMMENT = (
    "GENERATED by hooks/build_hooks.py from the table of ТЗ §8.1 — do not edit by hand; "
    "run `python hooks/build_hooks.py` (CI runs it with --check). Each command hook is emitted in "
    "three exec-form variants (python / python3 / py -3) because no single interpreter name works "
    "on every host; duplicate firings are harmless — permission_gate is deterministic and "
    "progress_logger deduplicates by events/.seen/<event_key> (§7.2 C). The hooks only ever answer "
    "`{}` or `allow`: they never deny, so user deny/ask rules keep precedence. Two fallbacks are "
    "generated on demand: --inline-fallback (a python -c one-liner of the fetch gate, for a failed "
    "probe P2) and --agent-fallback (an enumerated ^memoforge:(...)$ matcher from lib/models.md, "
    "for a failed probe P9)."
)

INLINE_FALLBACK_COMMENT = "fallback_if_exec_form_fails"


# --- pieces ---------------------------------------------------------------


def script_path(script: str) -> str:
    """`${CLAUDE_PLUGIN_ROOT}/hooks/<script>` — substituted as a plain string in exec form."""
    return f"{PLUGIN_ROOT_PLACEHOLDER}/hooks/{script}"


def interpreter_variants(script: str, args: tuple) -> list:
    """The three exec-form hook entries of one row (§8.1)."""
    entries = []
    for command, prefix in INTERPRETERS:
        entries.append(
            {
                "type": "command",
                "command": command,
                "args": list(prefix) + [script_path(script)] + list(args),
            }
        )
    return entries


def read_allowlist(root: Path) -> list:
    """Active hosts of `hooks/allowlist.txt` (comments stripped, so `optional` stays out)."""
    path = root / "hooks" / ALLOWLIST_FILENAME
    try:
        raw = path.read_text(encoding="utf-8-sig")
    except OSError:
        return []
    hosts = []
    for line in raw.split("\n"):
        host = line.split("#", 1)[0].strip().lower()
        if host and host not in hosts:
            hosts.append(host)
    return sorted(hosts)


def agent_names(root: Path) -> list:
    """Agent names of the `lib/models.md` table — the source of the enumerated matcher (§8.1)."""
    try:
        raw = (root / MODELS_RELATIVE).read_text(encoding="utf-8-sig")
    except OSError:
        return []
    names = []
    for line in raw.split("\n"):
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [cell.strip() for cell in line.strip("|").split("|")]
        if not cells:
            continue
        name = cells[0].strip("`")
        if name and name != cells[0] and re.fullmatch(r"[a-z0-9][a-z0-9-]*", name) and name not in names:
            names.append(name)
    return names


def agent_fallback_matcher(root: Path) -> str:
    """`^memoforge:(legal-researcher|…)$`; falls back to the prefix when `models.md` is unreadable."""
    names = agent_names(root)
    if not names:
        return AGENT_PREFIX_MATCHER
    return "^memoforge:(" + "|".join(names) + ")$"


def inline_fallback_command(hosts: list) -> str:
    """One-line shell-form twin of `permission_gate.py --mode fetch`, built from the allowlist.

    Only single quotes are used inside, so the string survives both `bash -c "…"` and PowerShell.
    Its one divergence from the script: a body that starts with `{` but is not valid JSON raises,
    the hook exits non-zero and Claude Code treats it as «no hook» — the same effective decision as
    `{}`, only louder in the logs. That is acceptable for a break-glass path.
    """
    code = (
        "import json,sys;from urllib.parse import urlparse as P;"
        "A=frozenset('" + " ".join(hosts) + "'.split());"
        "s=sys.stdin.buffer.read().decode('utf-8-sig','replace');"
        "d=json.loads(s) if s.strip()[:1]=='{' else {};"
        "t=d.get('tool_input') if isinstance(d,dict) else None;"
        "v=[t.get(k) for k in ('url','uri','link','href')] if isinstance(t,dict) else [];"
        "h=[(P(x.strip()).hostname or '').lower() for x in v if isinstance(x,str) and x.strip()];"
        "ok=bool(h) and all(y and (y in A or any(y.endswith('.'+a) for a in A)) for y in h);"
        "sys.stdout.write(json.dumps({'hookSpecificOutput':{'hookEventName':'PreToolUse',"
        "'permissionDecision':'allow','permissionDecisionReason':"
        "'memoforge legal-research allowlist: '+', '.join(h)}}) if ok else '{}')"
    )
    return 'python -c "' + code + '"'


# --- document -------------------------------------------------------------


def build(root: Path | None = None, inline_fallback: bool = False, agent_fallback: bool = False) -> dict:
    """The whole `hooks.json` document (§8.1)."""
    root = Path(root) if root is not None else PLUGIN_ROOT
    fallback_matcher = agent_fallback_matcher(root) if agent_fallback else None

    grouped: dict = {}
    for row in ROWS:
        block: dict = {}
        matcher = row["matcher"]
        if row.get("agent_matcher") and fallback_matcher:
            matcher = fallback_matcher
        if matcher is not None:
            block["matcher"] = matcher
        entries = interpreter_variants(row["script"], row["args"])
        if row.get("async"):
            for entry in entries:
                entry["async"] = True
        block["hooks"] = entries
        grouped.setdefault(row["event"], []).append(block)

    if inline_fallback:
        grouped.setdefault("PreToolUse", []).append(
            {
                "_comment": INLINE_FALLBACK_COMMENT,
                "matcher": FETCH_MATCHER,
                "hooks": [{"type": "command", "command": inline_fallback_command(read_allowlist(root))}],
            }
        )

    hooks = {event: grouped[event] for event in EVENT_ORDER if event in grouped}
    return {"_comment": FILE_COMMENT, "hooks": hooks}


def render(root: Path | None = None, inline_fallback: bool = False, agent_fallback: bool = False) -> str:
    """The exact bytes of `hooks/hooks.json` (a trailing newline, indent 2)."""
    document = build(root, inline_fallback=inline_fallback, agent_fallback=agent_fallback)
    return json.dumps(document, ensure_ascii=False, indent=2) + "\n"


# --- command --------------------------------------------------------------


def main(argv: list | None = None) -> int:
    """Write or verify `hooks/hooks.json`; returns the process exit code."""
    parser = argparse.ArgumentParser(description="generate hooks/hooks.json from ТЗ §8.1")
    parser.add_argument("--root", default=None, help="plugin root (default: the file's own root)")
    parser.add_argument("--out", default=None, help="write here instead of <root>/hooks/hooks.json")
    parser.add_argument("--check", action="store_true", help="compare only; exit 1 on a mismatch")
    parser.add_argument("--inline-fallback", action="store_true", help="add the python -c fetch block (P2)")
    parser.add_argument("--agent-fallback", action="store_true", help="enumerate agents in the matcher (P9)")
    args = parser.parse_args(argv)

    root = Path(args.root) if args.root else PLUGIN_ROOT
    path = Path(args.out) if args.out else root / "hooks" / HOOKS_FILENAME
    content = render(root, inline_fallback=args.inline_fallback, agent_fallback=args.agent_fallback)

    if args.check:
        try:
            current = path.read_text(encoding="utf-8-sig")
        except OSError:
            current = None
        if current == content:
            sys.stdout.write(json.dumps({"path": str(path), "check": True, "up_to_date": True}) + "\n")
            return 0
        sys.stdout.write(
            json.dumps(
                {
                    "path": str(path),
                    "check": True,
                    "up_to_date": False,
                    "errors": ["hooks_json_out_of_date: run `python hooks/build_hooks.py`"],
                }
            )
            + "\n"
        )
        return 1

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content.encode("utf-8"))
    sys.stdout.write(json.dumps({"path": str(path), "written": True, "bytes": len(content)}) + "\n")
    return 0


def _utf8_stdout() -> None:
    """CONVENTIONS: a hook may print a path or a host that the console codepage cannot encode."""
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, OSError, ValueError):
        pass


if __name__ == "__main__":
    _utf8_stdout()
    sys.exit(main())
